const glyphs={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
const initial=['br','bn','bb','bq','bk','bb','bn','br','bp','bp','bp','bp','bp','bp','bp','bp','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','wp','wp','wp','wp','wp','wp','wp','wp','wr','wn','wb','wq','wk','wb','wn','wr'];
// Keep exactly four empty ranks between the two armies.
initial.splice(16, initial.length - 32, ...Array(32).fill(''));
let board=[],turn='w',selected=null,legal=[],history=[],flipped=false,clocks={w:600,b:600},timer=null,finished=false;
const $=id=>document.getElementById(id),files='abcdefgh';
function reset(){board=[...initial];turn='w';selected=null;legal=[];history=[];clocks={w:600,b:600};finished=false;$('move-list').innerHTML='';render();startClock()}
function xy(i){return [i%8,Math.floor(i/8)]}function ix(x,y){return y*8+x}function inside(x,y){return x>=0&&x<8&&y>=0&&y<8}function color(p){return p&&p[0]}function enemy(a,b){return a&&b&&color(a)!==color(b)}
function movesAt(i,attack=false){const p=board[i];if(!p)return[];const c=p[0],t=p[1],[x,y]=xy(i),out=[],add=(a,b)=>{if(inside(a,b)&&(!board[ix(a,b)]||enemy(p,board[ix(a,b)])))out.push(ix(a,b))},slide=(dirs)=>dirs.forEach(([dx,dy])=>{let a=x+dx,b=y+dy;while(inside(a,b)){let q=board[ix(a,b)];if(!q)out.push(ix(a,b));else{if(enemy(p,q))out.push(ix(a,b));break}a+=dx;b+=dy}});
if(t==='p'){let d=c==='w'?-1:1,home=c==='w'?6:1;if(attack){[-1,1].forEach(dx=>{if(inside(x+dx,y+d))out.push(ix(x+dx,y+d))})}else{if(inside(x,y+d)&&!board[ix(x,y+d)]){out.push(ix(x,y+d));if(y===home&&!board[ix(x,y+2*d)])out.push(ix(x,y+2*d))}[-1,1].forEach(dx=>{if(inside(x+dx,y+d)&&enemy(p,board[ix(x+dx,y+d)]))out.push(ix(x+dx,y+d))})}}if(t==='n')[[1,2],[2,1],[2,-1],[1,-2],[-1,-2],[-2,-1],[-2,1],[-1,2]].forEach(d=>add(x+d[0],y+d[1]));if(t==='b'||t==='q')slide([[1,1],[1,-1],[-1,1],[-1,-1]]);if(t==='r'||t==='q')slide([[1,0],[-1,0],[0,1],[0,-1]]);if(t==='k')[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]].forEach(d=>add(x+d[0],y+d[1]));return out}
function attacked(square,by){return board.some((p,i)=>p&&p[0]===by&&movesAt(i,true).includes(square))}function inCheck(c){let k=board.findIndex(p=>p===c+'k');return k>=0&&attacked(k,c==='w'?'b':'w')}
function safeMoves(i){return movesAt(i).filter(to=>{let a=board[i],b=board[to];board[to]=a;board[i]='';let bad=inCheck(a[0]);board[i]=a;board[to]=b;return !bad})}
function notation(p,from,to,take){let [x,y]=xy(to),name=p[1]==='p'?'':p[1].toUpperCase();return name+(take?'x':'')+files[x]+(8-y)}
function choose(i){if(finished)return;let p=board[i];if(selected!==null&&legal.includes(i)){let piece=board[selected],taken=board[i],from=selected;history.push({board:[...board],turn,clocks:{...clocks}});board[i]=piece;board[selected]='';let [,y]=xy(i);if(piece[1]==='p'&&(y===0||y===7))board[i]=piece[0]+'q';$('move-list').insertAdjacentHTML('beforeend',`<li>${notation(piece,from,i,!!taken)}</li>`);turn=turn==='w'?'b':'w';selected=null;legal=[];if(inCheck(turn))$('status').textContent=`${turn==='w'?'White':'Black'} is in check`;render();return}if(p&&p[0]===turn){selected=i;legal=safeMoves(i)}else{selected=null;legal=[]}render()}
function render(){const root=$('board');root.innerHTML='';let order=[...Array(64).keys()];if(flipped)order.reverse();order.forEach(i=>{let [x,y]=xy(i),p=board[i],b=document.createElement('button');b.className=`square ${(x+y)%2?'dark':'light'} ${i===selected?'selected':''} ${legal.includes(i)?(p?'capture':'legal'):''}`;b.onclick=()=>choose(i);b.innerHTML=`${p?`<span class="piece ${p[0]==='w'?'white':'black'}">${glyphs[p[0]][p[1]]}</span>`:''}${x===0?`<i class="coord rank">${8-y}</i>`:''}${y===7?`<i class="coord file">${files[x]}</i>`:''}`;root.appendChild(b)});if(!inCheck(turn)&&!finished)$('status').textContent=`${turn==='w'?'White':'Black'} to move`;updateClocks()}
function updateClocks(){['w','b'].forEach(c=>$(c==='w'?'white-clock':'black-clock').textContent=`${String(Math.floor(clocks[c]/60)).padStart(2,'0')}:${String(clocks[c]%60).padStart(2,'0')}`)}function startClock(){clearInterval(timer);timer=setInterval(()=>{if(!finished&&clocks[turn]>0){clocks[turn]--;updateClocks();if(!clocks[turn]){$('status').textContent=`${turn==='w'?'White':'Black'} ran out of time`;finished=true}}},1000)}
$('new-game').onclick=reset;$('flip').onclick=()=>{flipped=!flipped;render()};$('undo').onclick=()=>{let h=history.pop();if(!h)return;board=h.board;turn=h.turn;clocks=h.clocks;$('move-list').lastElementChild?.remove();selected=null;legal=[];render()};reset();
